version: "3.7"

services:
  dpp:
    container_name: dpp
    image: local.dpp
    environment:
      LOG_LEVEL: "info"
      TRANSPORT_MODE: 'hybrid'
    ports:
      - "8445:8445"
    networks:
      - regtest-stack

networks:
  regtest-stack:
    external: true
    name: regtest-stack
